FROM ghcr.io/luxonis/robothub-app-v2:2024.110.1321-rvc2-regular

RUN pip3 install --target /lib --upgrade --extra-index-url https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/ --no-cache-dir depthai==2.23.0.0.dev0+220370fc0a68ab14d6eea043fb5f325c1994bc12