config_version = "2.0"
configuration = []

[info]
name = "RAE Default Application"
description = "RAE Default Application"

[runtime]
application = "src/follow_me.py#Application"
workdir = "/app"
pre_launch = "export ROS_DOMAIN_ID=30\n. /opt/ros/$ROS_DISTRO/setup.sh\n. /ws/install/setup.sh && export LD_LIBRARY_PATH=/usr/local/lib/python3.10/dist-packages${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
permissions = ["rae-peripherals"]

[runtime.frontend]
redirectToIndex = true

[runtime.runs_on]
type = "image"
name = "luxonis/rae-ros-robot:dai_ros_py_sound"
