config_version = "2.0"

[info]
name = "RGB Stream"
description = "This app streams from the RGB sensor of each assigned device"

[runtime]
application = "app.py#ExampleApplication"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.218.1205-regular"

[[configuration]]
label = "Stream FPS"
key = "stream_fps"
title = "Stream FPS"
description = "Stream FPS"
field = "num_range"
step = 1.0
min = 0.0
max = 60.0
initial_value = 30.0
