config_version = "2.0"
configuration = []

[info]
name = "Line Cross Counter app"
description = "This app counts the number of times a line is crossed by people."

[runtime]
application = "app.py#LineCrossApplication"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.218.1205-regular"
